name: autoguard
description: "Autoguard, tu recepcionista personal"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.3
  dart_openai: ^5.1.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_ui_firestore: ^1.6.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/profile_picture.png
    - assets/autoguard_logo.jpg
    - assets/autoguard_logo_app.jpg

flutter_native_splash:
  color: "#42f59e"

  android_12:
    color: "#42f59e"
