// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvKfJFwss8yAhmmrvWtyGLNSIX2s9-MTo',
    appId: '1:851216697180:web:95c2c9b97e717246292399',
    messagingSenderId: '851216697180',
    projectId: 'smartguard-dc90b',
    authDomain: 'smartguard-dc90b.firebaseapp.com',
    storageBucket: 'smartguard-dc90b.appspot.com',
    measurementId: 'G-RZGQK6JY3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDLmRVoo9ZxtJNMN_ionN_j1DLIApTDKU',
    appId: '1:851216697180:android:be8b104a69ec77d1292399',
    messagingSenderId: '851216697180',
    projectId: 'smartguard-dc90b',
    storageBucket: 'smartguard-dc90b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRe9sVqvJCB0EeEiNnzS_1w-JvOz6_20U',
    appId: '1:851216697180:ios:bc437970986aedc0292399',
    messagingSenderId: '851216697180',
    projectId: 'smartguard-dc90b',
    storageBucket: 'smartguard-dc90b.appspot.com',
    iosBundleId: 'com.example.autoguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRe9sVqvJCB0EeEiNnzS_1w-JvOz6_20U',
    appId: '1:851216697180:ios:bc437970986aedc0292399',
    messagingSenderId: '851216697180',
    projectId: 'smartguard-dc90b',
    storageBucket: 'smartguard-dc90b.appspot.com',
    iosBundleId: 'com.example.autoguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvKfJFwss8yAhmmrvWtyGLNSIX2s9-MTo',
    appId: '1:851216697180:web:c9bbe5801eff4924292399',
    messagingSenderId: '851216697180',
    projectId: 'smartguard-dc90b',
    authDomain: 'smartguard-dc90b.firebaseapp.com',
    storageBucket: 'smartguard-dc90b.appspot.com',
    measurementId: 'G-CSEDMHST80',
  );

}